/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather */
        get: operations["weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get States
         * @description Every analysed frame's full state, in order.
         *
         *     This is the replay path. With per-frame state on the client, the UI can step through
         *     a session and show exactly what the system knew at each moment — which is what Phase
         *     4's WebSocket would have delivered visually, without the socket.
         */
        get: operations["get_states_api_sessions__session_id__states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Frames */
        post: operations["upload_frames_api_sessions__session_id__frames_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/sample/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse Sample
         * @description One-click demo path. Same pipeline as an upload, no file transfer.
         */
        post: operations["analyse_sample_api_sessions__session_id__sample__sample_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Video
         * @description Extract and classify synchronously. Phase 4 makes this a real background job.
         */
        post: operations["upload_video_api_sessions__session_id__video_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_frames_api_sessions__session_id__frames_post */
        Body_upload_frames_api_sessions__session_id__frames_post: {
            /** Files */
            files: string[];
        };
        /** Body_upload_video_api_sessions__session_id__video_post */
        Body_upload_video_api_sessions__session_id__video_post: {
            /** File */
            file: string;
        };
        /**
         * ClassProbabilities
         * @description A full distribution, never an argmax — the spread is the drying signal.
         */
        ClassProbabilities: {
            /** Dry */
            dry: number;
            /** Damp */
            damp: number;
            /** Wet */
            wet: number;
            /** Standing Water */
            standing_water: number;
        };
        /**
         * Crossover
         * @description Null on the wire whenever any gate in SPEC-ANALYSIS B.5 fails. Never fabricated.
         */
        Crossover: {
            /**
             * Target Compound
             * @enum {string}
             */
            target_compound: "SLICK" | "INTERMEDIATE" | "FULL_WET";
            /** Threshold */
            threshold: number;
            /** Eta S */
            eta_s: number;
            /** Eta Optimistic S */
            eta_optimistic_s: number;
            /** Eta Pessimistic S */
            eta_pessimistic_s: number;
        };
        /**
         * FrameClassification
         * @description One analysed frame — the history the timeline and the projection chart plot.
         *
         *     `twi` and `quality_score` are null only for frames stored before the analysis layer
         *     existed; every frame written since Phase 2 carries them.
         */
        FrameClassification: {
            /** Frame Index */
            frame_index: number;
            /** T S */
            t_s: number;
            probabilities: components["schemas"]["ClassProbabilities"];
            /**
             * Dominant Class
             * @enum {string}
             */
            dominant_class: "dry" | "damp" | "wet" | "standing_water";
            /** Twi */
            twi?: number | null;
            /** Quality Score */
            quality_score?: number | null;
        };
        /** FrameQuality */
        FrameQuality: {
            /** Score */
            score: number;
            /** Blur */
            blur: number;
            /** Clipping */
            clipping: number;
            /** Entropy */
            entropy: number;
        };
        /** Fusion */
        Fusion: {
            /** Visual Weight */
            visual_weight: number;
            /** Weather Weight */
            weather_weight: number;
            /** Weather Rate Prior */
            weather_rate_prior: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Model Id */
            model_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "zero-shot" | "probe";
            /** Device */
            device: string;
            /** Warm */
            warm: boolean;
            /** Weather Cache Age S */
            weather_cache_age_s: number | null;
            /** Warmup Ms */
            warmup_ms?: number | null;
            thresholds: components["schemas"]["Thresholds"];
        };
        /** Recommendation */
        Recommendation: {
            /**
             * Current
             * @enum {string}
             */
            current: "SLICK" | "INTERMEDIATE" | "FULL_WET";
            /** Next */
            next: ("SLICK" | "INTERMEDIATE" | "FULL_WET") | null;
            /**
             * State
             * @enum {string}
             */
            state: "HOLD" | "ARMING" | "BOX";
            /** Windows Held */
            windows_held: number;
            /** Windows Required */
            windows_required: number;
            /** Rationale */
            rationale: string;
        };
        /**
         * Sample
         * @description Bundled demo footage. `story` is what a judge should watch for.
         */
        Sample: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Story */
            story: string;
            /** Duration S */
            duration_s: number;
        };
        /** SessionCreate */
        SessionCreate: {
            /** Name */
            name: string;
            /** Source */
            source?: string | null;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Session Id */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Name */
            name: string;
            /** Source */
            source: string | null;
            /** Frames */
            frames: components["schemas"]["FrameClassification"][];
            state: components["schemas"]["TrackState"] | null;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Session Id */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Name */
            name: string;
        };
        /**
         * Thresholds
         * @description The tuned constants the interface has to draw, served rather than re-typed.
         *
         *     Compound boundaries, the quality flag and the two frame-quality reference values were
         *     all hardcoded a second time in the frontend. Retuning `config.py` left the chart
         *     silently disagreeing with the pit call it sits beside — the analysis was right and the
         *     picture of it was wrong, which is the worst of both.
         */
        Thresholds: {
            /** Compound Low */
            compound_low: number;
            /** Compound High */
            compound_high: number;
            /** Quality Flag */
            quality_flag: number;
            /** Blur Reference */
            blur_reference: number;
            /** Clipping Tolerance */
            clipping_tolerance: number;
            /** Trend R2 Min */
            trend_r2_min: number;
            /** Trend Rate Min */
            trend_rate_min: number;
        };
        /**
         * TrackState
         * @description The single object the whole UI renders from.
         */
        TrackState: {
            /** Session Id */
            session_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Twi */
            twi: number;
            /** Twi Raw */
            twi_raw: number;
            probabilities: components["schemas"]["ClassProbabilities"];
            /**
             * Dominant Class
             * @enum {string}
             */
            dominant_class: "dry" | "damp" | "wet" | "standing_water";
            trend: components["schemas"]["Trend"];
            crossover: components["schemas"]["Crossover"] | null;
            recommendation: components["schemas"]["Recommendation"];
            frame_quality: components["schemas"]["FrameQuality"];
            fusion: components["schemas"]["Fusion"];
            /** Frame Index */
            frame_index: number;
            /** Thumbnail Url */
            thumbnail_url: string | null;
        };
        /** Trend */
        Trend: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "DRYING" | "WETTING" | "STABLE";
            /** Rate Per Min */
            rate_per_min: number;
            /** R Squared */
            r_squared: number;
            /** Window S */
            window_s: number;
            /** Sufficient Signal */
            sufficient_signal: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoUploadResponse */
        VideoUploadResponse: {
            /** Job Id */
            job_id: string;
            /** Frame Count */
            frame_count: number;
            /** Duration S */
            duration_s: number;
        };
        /**
         * WeatherResponse
         * @description Normalised conditions plus the drying prior derived from them (B.7).
         */
        WeatherResponse: {
            /** Temperature C */
            temperature_c: number;
            /** Wind Speed Kmh */
            wind_speed_kmh: number;
            /** Relative Humidity */
            relative_humidity: number;
            /** Cloud Cover */
            cloud_cover: number;
            /** Precipitation Mm H */
            precipitation_mm_h: number;
            /**
             * Source
             * @enum {string}
             */
            source: "open-meteo" | "offline-fallback";
            /** Drying Rate Prior */
            drying_rate_prior: number;
            /** Cache Age S */
            cache_age_s: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    weather_api_weather_get: {
        parameters: {
            query?: {
                lat?: number;
                lon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_states_api_sessions__session_id__states_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackState"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_frames_api_sessions__session_id__frames_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_frames_api_sessions__session_id__frames_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameClassification"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sample"][];
                };
            };
        };
    };
    analyse_sample_api_sessions__session_id__sample__sample_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_api_sessions__session_id__video_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_api_sessions__session_id__video_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
